export const CAMERA_CONFIG = {
  lookSensitivityX: 0.0035,
  lookSensitivityY: 0.0025,
  zoomSensitivity: 0.01,
  zoomMin: 6.5,
  zoomMax: 24,
  manualLookDeadZone: 1.2,
  recenterDelay: 0.3,
  targetLerpXZ: 7,
  targetLerpY: 5,
  positionLerp: 7,
  damageShakeFrequency: 38,
  damageShakeAmplitude: 0.28,
  movementSwayFrequency: 0.12,
  movementSwayAmplitude: 0.1,
  onFoot: {
    baseYaw: -0.75,
    basePitch: 0.62,
    baseDistance: 16,
    targetHeight: 1.45,
    autoPitch: 0.56,
    autoDistance: 10.5,
    autoYawLerp: 4.2,
    autoPitchLerp: 2.1,
    autoDistanceLerp: 1.8,
    moveThreshold: 0.35,
    lookAhead: 2.5,
    followHeadingLerp: 9.5,
    followCarry: 0.22,
    velocityLead: 0.12,
  },
  driving: {
    targetHeight: 2.3,
    autoYawOffset: -0.18,
    autoPitch: 0.5,
    autoDistance: 13.5,
    autoYawLerp: 2.4,
    autoPitchLerp: 1.4,
    autoDistanceLerp: 1.15,
    lookAheadBase: 4.5,
    lookAheadSpeedFactor: 0.18,
    lookAheadMaxBonus: 6,
  },
};

export const HUD_CONFIG = {
  maxWantedStars: 5,
  damageFlashFade: 2.9,
  damageNoticeFade: 3.8,
  eventPulseFade: 2.2,
};

export const UI_TEXT = {
  header: {
    eyebrow: "CINEMATIC DISTRICT RUN",
    controlsLabel: "Ruch",
    controlsValue: "Strzalki / Shift / E / F / R",
    cameraLabel: "Kamera",
    cameraValue: "Mysz + kolko",
  },
  overlay: {
    eyebrow: "GOLDEN HOUR LOCKDOWN",
    lead:
      "Przejmij auto, zgarnij target gotowki i przetrwaj policyjny nacisk w jednej filmowej rundzie po Harbor Heights.",
    startButton: "Rozpocznij run",
  },
  hud: {
    objectiveTitle: "Cel",
    controlsTitle: "Sterowanie",
    statusTitle: "Status",
    districtTitle: "Dzielnica",
    runTitle: "Run",
    audioTitle: "Audio",
    defaultObjective:
      "Przejmij auto, zbieraj paczki i dociagnij wynik do targetu zanim skonczy sie czas.",
    controls: [
      "Strzalki: ruch / jazda",
      "Shift: sprint",
      "E: wsiadz / wysiadz",
      "LPM / F: strzal",
      "Spacja: reczny",
      "R: reset / restart rundy",
      "Mysz: obrot kamery",
      "Kolko: zoom",
    ],
    statusReady: "Gotowy do wjazdu",
    statusGameOver: "Run zakonczony",
    statusVehicle: "W aucie",
    statusOnFoot: "Na piechote",
    cashLabel: "Gotowka",
    wantedLabel: "Poscig",
    healthLabel: "Zdrowie",
    speedLabel: "Predkosc",
    trafficLabel: "Ruch",
    fpsLabel: "FPS",
    timerLabel: "Czas",
    scoreLabel: "Wynik",
    targetLabel: "Target",
    bonusLabel: "Heat bonus",
    eventLabel: "Event",
    eventIdle: "Lokalne radio szuka nastepnej okazji",
    recentLabel: "Ostatni impuls",
    audioOn: "Audio: ON",
    audioOff: "Audio: OFF",
    muteButton: "Wycisz",
    unmuteButton: "Wlacz",
    restartHint: "R restartuje run po porazce",
    damageHit: "Uderzenie",
    damageSources: {
      collision: "mocne uderzenie",
      traffic: "ruch uliczny",
      police: "kontakt z policja",
      gunfire: "ostrzal",
    },
  },
  endOverlay: {
    eyebrow: "RUN SUMMARY",
    survivedTitle: "Dzielnica odpuscila",
    failedTitle: "Miasto cie dogonilo",
    timeoutTitle: "Czas rundy minal",
    summaryLead: "Jeszcze jeden wjazd i mozna podbic wynik.",
    scoreLabel: "Wynik",
    cashLabel: "Gotowka",
    heatLabel: "Heat bonus",
    eventLabel: "Event bonus",
    retryButton: "Jeszcze jeden run",
  },
  startControls: [
    ["Strzalki / WASD", "Ruch i jazda"],
    ["Shift", "Sprint pieszo"],
    ["E", "Wejscie i wyjscie z auta"],
    ["LPM / F", "Strzal z broni"],
    ["Spacja", "Hamulec reczny"],
    ["R", "Reset pozycji / restart rundy"],
    ["Mysz / kolko", "Obrot i zoom kamery"],
  ],
};

export const OBJECTIVE_TEXT = {
  intro: "Przejmij auto i ustaw tempo, zanim Harbor Heights zamknie wszystkie drogi.",
  onFootHint: "Na piechote jestes zwrotniejszy, ale trudniej zgubisz poscig.",
  weaponFire: "Bron aktywna. Strzaly podbijaja poziom poscigu.",
  pedShot: "Postrzal. Ulica robi sie goraca.",
  vehicleShot: "Trafiles pojazd. Kierowcy spanikowali.",
  policeShot: "Ostrzelales policje. Poscig eskaluje.",
  vehicleHint: "Masz fure. Dociskaj target gotowki i uwazaj na policje.",
  pickup: "Zgarniete. Cisnij dalej, dopoki ruch sie nie zamknie.",
  pedHit: "Masz krew na zderzaku. Policja natychmiast ruszyla.",
  vehicleReset: "Auto wrocilo na trase. Ruszaj dalej.",
  playerReset: "Wrociles na start dzielnicy.",
  onFootWanted: "Jestes sledzony. Schowaj sie albo dorwij auto, by zgubic radiowozy.",
  recovery: "Silnik znowu ciagnie. Wcisnij gaz i wyjedz z klinczu.",
  eventHighValue: "Lokalny cynk: jedna paczka ma wiekszy payout. Zlap ja, zanim okazja zniknie.",
  eventCourier:
    "Kurier pod presja: utrzymaj tempo w aucie przez kilka sekund, a miasto zaplaci za ryzyko.",
  eventHeat: "Goraca strefa: przetrwaj chwile pod poscigiem, aby skasowac heat bonus.",
  eventComplete: "Bonus domkniety. Ulica na chwile nalezy do ciebie.",
  eventFailed: "Okazja przepadla. Miasto wystawi kolejna, jesli utrzymasz tempo.",
  heatBonus: "Heat bonus rosnie. Trzymaj nerwy, a wynik skoczy.",
  runTarget: "Target coraz blizej. Jeszcze troche i run bedzie wygrany na punktach.",
  timeUp: "Czas rundy minal. Wynik zostal zamkniety.",
  gameOver: "Koniec runu. Wcisnij R albo wybierz kolejny wjazd.",
};
