export const CAMERA_CONFIG = {
  lookSensitivityX: 0.0035,
  lookSensitivityY: 0.0025,
  zoomSensitivity: 0.01,
  zoomMin: 6.5,
  zoomMax: 24,
  manualLookDeadZone: 1.2,
  recenterDelay: 0.3,
  targetLerpXZ: 7,
  targetLerpY: 5,
  positionLerp: 7,
  damageShakeFrequency: 38,
  damageShakeAmplitude: 0.28,
  movementSwayFrequency: 0.12,
  movementSwayAmplitude: 0.1,
  onFoot: {
    baseYaw: -0.28,
    basePitch: 0.46,
    baseDistance: 13.5,
    targetHeight: 1.45,
    autoPitch: 0.48,
    autoDistance: 9.8,
    autoYawLerp: 4.2,
    autoPitchLerp: 2.1,
    autoDistanceLerp: 1.8,
    moveThreshold: 0.35,
    lookAhead: 3.6,
    followHeadingLerp: 9.5,
    followCarry: 0.22,
    velocityLead: 0.12,
  },
  driving: {
    targetHeight: 2.3,
    autoYawOffset: -0.18,
    autoPitch: 0.5,
    autoDistance: 13.5,
    autoYawLerp: 2.4,
    autoPitchLerp: 1.4,
    autoDistanceLerp: 1.15,
    lookAheadBase: 4.5,
    lookAheadSpeedFactor: 0.18,
    lookAheadMaxBonus: 6,
  },
};

export const HUD_CONFIG = {
  maxWantedStars: 5,
  damageFlashFade: 2.9,
  damageNoticeFade: 3.8,
  eventPulseFade: 2.2,
};

export const UI_TEXT = {
  header: {
    eyebrow: "SUNSET CHASE SHOWCASE",
    controlsLabel: "Ruch",
    controlsValue: "Strzalki / Shift / E / F / R",
    cameraLabel: "Kamera",
    cameraValue: "Mysz + kolko",
  },
  overlay: {
    eyebrow: "HARBOR HEAT",
    lead:
      "Wskocz do miasta skapanego w zachodzie slonca, przejmij auto i utrzymaj tempo, zanim policyjna obrecz zamknie Harbor Heights.",
    startButton: "Odpal przejazd",
  },
  hud: {
    objectiveTitle: "Cel",
    controlsTitle: "Sterowanie",
    statusTitle: "Status",
    districtTitle: "Dzielnica",
    runTitle: "Run",
    audioTitle: "Audio",
    defaultObjective:
      "Przejmij auto, zbieraj paczki i dowiez target, zanim policyjne radio zamknie cala siatke ulic.",
    controls: [
      "Strzalki: ruch / jazda",
      "Shift: sprint",
      "E: wsiadz / wysiadz",
      "LPM / F: strzal",
      "Spacja: reczny",
      "R: reset / restart rundy",
      "Mysz: obrot kamery",
      "Kolko: zoom",
    ],
    statusReady: "Silnik czeka",
    statusGameOver: "Przejazd zakonczony",
    statusPaused: "Przejazd wstrzymany",
    statusVehicle: "Za kierownica",
    statusOnFoot: "Na piechote",
    cashLabel: "Gotowka",
    wantedLabel: "Poscig",
    healthLabel: "Zdrowie",
    speedLabel: "Predkosc",
    trafficLabel: "Ruch",
    fpsLabel: "FPS",
    timerLabel: "Czas",
    scoreLabel: "Wynik",
    targetLabel: "Target",
    bonusLabel: "Heat bonus",
    eventLabel: "Event",
    eventIdle: "Miasto szykuje kolejny impuls",
    recentLabel: "Ostatni impuls",
    audioOn: "Audio: ON",
    audioOff: "Audio: OFF",
    qualityLabel: "Jakosc",
    qualityLow: "LOW",
    qualityMedium: "MEDIUM",
    qualityHigh: "HIGH",
    muteButton: "Wycisz",
    unmuteButton: "Wlacz",
    qualityButton: "Przelacz preset",
    restartHint: "R restartuje przejazd po porazce",
    pauseHint: "P pauzuje i wznawia przejazd",
    damageHit: "Uderzenie",
    damageSources: {
      collision: "mocne uderzenie",
      traffic: "ruch uliczny",
      police: "kontakt z policja",
      gunfire: "ostrzal",
    },
  },
  endOverlay: {
    eyebrow: "RUN BREAKDOWN",
    survivedTitle: "Miasto zostalo za toba",
    failedTitle: "Ulica cie domknela",
    timeoutTitle: "Okno czasowe minelo",
    summaryLead: "Jeszcze jeden przejazd i wynik zrobi sie filmowy.",
    scoreLabel: "Wynik",
    cashLabel: "Gotowka",
    heatLabel: "Heat bonus",
    eventLabel: "Event bonus",
    retryButton: "Jeszcze jeden przejazd",
  },
  startControls: [
    ["Strzalki / WASD", "Ruch i jazda"],
    ["Shift", "Sprint pieszo"],
    ["E", "Wejscie i wyjscie z auta"],
    ["LPM / F", "Strzal z broni"],
    ["Spacja", "Hamulec reczny"],
    ["R", "Reset pozycji / restart rundy"],
    ["Mysz / kolko", "Obrot i zoom kamery"],
  ],
};

export const OBJECTIVE_TEXT = {
  intro: "Przejmij auto i narzuc tempo, zanim Harbor Heights obudzi cale policyjne radio.",
  onFootHint: "Na piechote jestes zwrotniejszy, ale ulica szybciej cie namierzy.",
  weaponFire: "Bron aktywna. Kazdy strzal podkreca poscig.",
  pedShot: "Postrzal. Chodniki juz wiedza, ze jest goraco.",
  vehicleShot: "Trafiles pojazd. Ruch natychmiast faluje.",
  policeShot: "Ostrzelales policje. Poscig przechodzi w twardy tryb.",
  vehicleHint: "Masz auto. Dociskaj target i nie daj sie wcisnac w korek.",
  pickup: "Zgarniete. Cisnij dalej, poki miasto zostawia szczeline.",
  pedHit: "Masz slady na zderzaku. Policja ruszyla od razu.",
  vehicleReset: "Auto wrocilo na asfalt. Ruszaj zanim okno sie zamknie.",
  playerReset: "Wrociles na start przejazdu.",
  onFootWanted: "Jestes sledzony. Dorwij auto albo schowaj sie za ruchem.",
  recovery: "Silnik zlapal oddech. Wcisnij gaz i uciekaj z klinczu.",
  eventHighValue: "Lokalny cynk: jedna paczka ma premium payout. Zlap ja, zanim zgasnie.",
  eventCourier:
    "Kurier pod cisnieniem: utrzymaj tempo w aucie przez kilka sekund, a dzielnica zaplaci za ryzyko.",
  eventHeat: "Goraca strefa: przetrwaj chwile pod poscigiem, zeby skasowac heat bonus.",
  eventComplete: "Bonus domkniety. Przez chwile cala os nalezy do ciebie.",
  eventFailed: "Okazja uciekla. Miasto wystawi nastepna, jesli utrzymasz flow.",
  heatBonus: "Heat bonus rosnie. Zachowaj zimna krew, a wynik odskoczy.",
  runTarget: "Target jest blisko. Jeszcze kawalek i zamkniesz przejazd na punktach.",
  timeUp: "Okno czasowe zamkniete. Wynik zostal zapisany.",
  gameOver: "Koniec przejazdu. Wcisnij R albo odpal kolejny wjazd.",
};
