export const WORLD_THEME = {
  skyTop: "#f6c27b",
  skyMid: "#df8d62",
  skyBottom: "#8fb2cc",
  fogColor: "#a6b6bf",
  fogStart: 165,
  fogEndFactor: 0.82,
  ambientSky: "#d7e6ef",
  ambientGround: "#475545",
  sunColor: "#ffd8aa",
  sunCore: "#ffd68d",
  sunHalo: "#ff9f64",
  rimColor: "#bfd8ef",
  skylineColor: "#53606b",
  skylineGlow: "#7f93a3",
  cloudColor: "#f8d6bc",
  groundTint: "#788763",
  grassColor: "#667658",
  groundShadowColor: "#374130",
  asphaltColor: "#3b3f46",
  roadColor: "#383c42",
  roadEdgeColor: "#535964",
  laneColor: "#f5e4bb",
  crosswalkColor: "#f4ead5",
  shoulderColor: "#2f353d",
  sidewalkColor: "#bdb09d",
  curbColor: "#92877a",
  planterStone: "#807565",
  planterLeaf: "#5f7c52",
  ringWallColor: "#5d625f",
  buildingShadow: "#2d3440",
  facadeAccent: "#d8c3ad",
  roofTrim: "#70747d",
  rooftopUnit: "#7f848c",
  lampMetal: "#5c6472",
  lampGlow: "#ffd196",
  lampPool: "#f2b664",
  glassColor: "#d1dde8",
  glassEdge: "#95b9d5",
  policeBlue: "#3b82f6",
  policeRed: "#ef4444",
  pickupGlow: "#f4c63d",
  signAccent: "#f05c37",
  bollardColor: "#69717a",
  hydrantColor: "#d24a3c",
  treeTrunk: "#745034",
  treeLeafDark: "#49674c",
  treeLeafLight: "#789a65",
  buildingPalette: ["#b77963", "#c7ab7d", "#76879b", "#7b8d74", "#995f54", "#c6bc9e"],
  roofPalette: ["#5d646d", "#72675e", "#4f5863"],
  shirtPalette: ["#a8554f", "#2b5f90", "#4f6b3c", "#a27c3e", "#5f4b8b"],
  textures: {
    asphaltBase: "/textures/asphalt-base.svg",
    asphaltNormal: "/textures/asphalt-normal.svg",
    concreteBase: "/textures/concrete-base.svg",
    concreteNormal: "/textures/concrete-normal.svg",
    facadeA: "/textures/facade-a.svg",
    facadeB: "/textures/facade-b.svg",
    roofBase: "/textures/roof-base.svg",
    roofNormal: "/textures/roof-normal.svg",
    glassBase: "/textures/glass-base.svg",
    metalDetail: "/textures/metal-detail.svg",
    paintDetail: "/textures/paint-detail.svg",
    foliageDetail: "/textures/foliage-detail.svg",
    grimeMask: "/textures/grime-mask.svg",
  },
};

const QUALITY_PRESETS = {
  low: {
    hardwareScale: 1.35,
    glowIntensity: 0.15,
    bloomThreshold: 0.94,
    bloomWeight: 0,
    fxaa: false,
    bloom: false,
    ssao: false,
    shadows: false,
    shadowMapSize: 0,
    shadowDarkness: 0,
    materialMode: "standard",
    textureDetail: 0.75,
    textureTileMultiplier: 0.8,
    normalStrength: 0.12,
    enableSecondaryDetail: false,
    enableGrime: false,
    enableVehicleLayers: false,
    enableCharacterLayers: false,
    buildingDetail: 0.65,
    vehicleDetail: 0.78,
    postExposure: 1.01,
    postContrast: 1.05,
  },
  medium: {
    hardwareScale: 1.05,
    glowIntensity: 0.24,
    bloomThreshold: 0.88,
    bloomWeight: 0.18,
    fxaa: true,
    bloom: true,
    ssao: false,
    shadows: true,
    shadowMapSize: 1024,
    shadowDarkness: 0.22,
    materialMode: "standard",
    textureDetail: 1,
    textureTileMultiplier: 1,
    normalStrength: 0.28,
    enableSecondaryDetail: true,
    enableGrime: false,
    enableVehicleLayers: true,
    enableCharacterLayers: true,
    buildingDetail: 1,
    vehicleDetail: 1,
    postExposure: 1.05,
    postContrast: 1.08,
  },
  high: {
    hardwareScale: 0.85,
    glowIntensity: 0.32,
    bloomThreshold: 0.82,
    bloomWeight: 0.28,
    fxaa: true,
    bloom: true,
    ssao: true,
    shadows: true,
    shadowMapSize: 2048,
    shadowDarkness: 0.34,
    materialMode: "pbr",
    textureDetail: 1.25,
    textureTileMultiplier: 1.12,
    normalStrength: 0.52,
    enableSecondaryDetail: true,
    enableGrime: true,
    enableVehicleLayers: true,
    enableCharacterLayers: true,
    buildingDetail: 1.2,
    vehicleDetail: 1.15,
    postExposure: 1.08,
    postContrast: 1.12,
  },
};

export function getQualityPreset(name = "medium") {
  return QUALITY_PRESETS[name] ?? QUALITY_PRESETS.medium;
}

export function canTriggerImpactPulse(lastPulseAt, now, cooldown = 0.18) {
  return lastPulseAt == null || now - lastPulseAt >= cooldown;
}
